# CAIA OMOP DQD Configuration
# Replace these values with your database details

# Database Connection
dbms: "spark"        # Options: "sql server", "snowflake", "spark", "postgresql", etc.
server: "databricks://adb-4068548029743470.10.azuredatabricks.net"       # Your database server
database: "data"     # Your OMOP database
user: "token"         # Your username
password: "NA"     # Your password
schema: "data.omop"             # Your OMOP schema
site_name: "JHU"    # Your site identifier

# Optional settings
port: null                # Only if non-standard port
warehouse: null           # For Snowflake only
connectionString: "jdbc:databricks://adb-4068548029743470.10.azuredatabricks.net:443/default;transportMode=http;ssl=1;AuthMech=3;httpPath=/sql/1.0/warehouses/ba264cbc3c5cca0d"    # For Databricks only
